version: '3.1'
services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: postgres_adminer
    restart: always
    ports:
      - 8888:8080