version: '3.3'
services:
  mysql8:
    image: 'mysql:8'
    container_name: mysql8
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: cloud 
      MYSQL_USER: uid
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Ho_Chi_Minh
    ports:
      - '3306:3306'
    expose:
      - '3306'

