services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: '${DB_PASSWORD:-changeme}'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        networks:
            - dev_tools
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - '${FORWARD_ADMINER_PORT:-8048}:8080'
        networks:
            - dev_tools

    mailhog:
        image: mailhog/mailhog:latest
        restart: always
        ports:
            - '${FORWARD_MAILHOG_WEB_PORT:-8025}:8025'
            - '${FORWARD_MAILHOG_SMTP_PORT:-1025}:1025'
        networks:
            - dev_tools

    mysql8:
        image: 'mysql:8'
        restart: always
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_DATABASE: cloud 
            MYSQL_USER: uid
            MYSQL_PASSWORD: pwd
            MYSQL_ROOT_PASSWORD: secret
            TZ: Asia/Ho_Chi_Minh
        ports:
            - '${FORWARD_MYSQL_PORT:-3306}:3306'
        networks:
            - dev_tools

    memcached:
        image: memcached:latest
        restart: always
        ports:
            - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
        networks:
            - dev_tools

    mongodb:
        image: 'mongo:latest'
        restart: always
        ports:
            - '${FORWARD_MONGO_PORT:-27017}:27017'
        networks:
            - dev_tools

    rabbitmq:
        image: 'rabbitmq:4.1-management-alpine'
        restart: always
        ports:
            - '${FORWARD_RABBITMQ_PORT:-5672}:5672'
            - '${FORWARD_RABBITMQ_WEB_PORT:-15672}:15672'
        networks:
            - dev_tools

    redis:
        image: 'bitnami/redis:latest'
        restart: always
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        networks:
            - dev_tools

networks:
    dev_tools:
        name: dev_tools
        driver: bridge

volumes:
    postgres_data:
