version: '3.3'
services:
  mysql8:
    image: 'mysql:8'
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'mysql8:/var/lib/mysql'

  memcached:
    container_name: memcached
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"

  mongodb:
    image: 'mongo:4.2.3-bionic'
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'

  rabbitmq:
    image: 'rabbitmq:3.8.0-management'
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

volumes:
  mysql8: null
